# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

workspace 'Runner'

project 'IJKMediaPlayer/IJKMediaPlayer.xcodeproj'

target 'IJKMediaPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IJKMediaPlayer

  target 'IJKMediaPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
